[2023-04-04 11:09:43 -0300] [60285] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:7000']
  backlog: 2048
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/real_time_chat_project/chat_service
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: gunicorn.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: chat:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7efc0735e8c0>
  on_reload: <function OnReload.on_reload at 0x7efc0735e9e0>
  when_ready: <function WhenReady.when_ready at 0x7efc0735eb00>
  pre_fork: <function Prefork.pre_fork at 0x7efc0735ec20>
  post_fork: <function Postfork.post_fork at 0x7efc0735ed40>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7efc0735ee60>
  worker_int: <function WorkerInt.worker_int at 0x7efc0735ef80>
  worker_abort: <function WorkerAbort.worker_abort at 0x7efc0735f0a0>
  pre_exec: <function PreExec.pre_exec at 0x7efc0735f1c0>
  pre_request: <function PreRequest.pre_request at 0x7efc0735f2e0>
  post_request: <function PostRequest.post_request at 0x7efc0735f370>
  child_exit: <function ChildExit.child_exit at 0x7efc0735f490>
  worker_exit: <function WorkerExit.worker_exit at 0x7efc0735f5b0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7efc0735f6d0>
  on_exit: <function OnExit.on_exit at 0x7efc0735f7f0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-04-04 11:09:43 -0300] [60285] [INFO] Starting gunicorn 20.1.0
[2023-04-04 11:09:43 -0300] [60285] [DEBUG] Arbiter booted
[2023-04-04 11:09:43 -0300] [60285] [INFO] Listening at: http://0.0.0.0:7000 (60285)
[2023-04-04 11:09:43 -0300] [60285] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-04-04 11:09:44 -0300] [60287] [INFO] Booting worker with pid: 60287
[2023-04-04 11:09:44 -0300] [60287] [DEBUG] Exception while loading the application
Traceback (most recent call last):
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/util.py", line 402, in import_app
    app = getattr(mod, name)
AttributeError: module 'chat' has no attribute 'application'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/util.py", line 406, in import_app
    raise AppImportError("Failed to find attribute %r in %r." % (name, module))
gunicorn.errors.AppImportError: Failed to find attribute 'application' in 'chat'.
[2023-04-04 11:09:44 -0300] [60287] [INFO] Worker exiting (pid: 60287)
[2023-04-04 11:09:44 -0300] [60288] [INFO] Booting worker with pid: 60288
[2023-04-04 11:09:44 -0300] [60285] [WARNING] Worker with pid 60288 was terminated due to signal 15
[2023-04-04 11:09:44 -0300] [60285] [INFO] Shutting down: Master
[2023-04-04 11:09:44 -0300] [60285] [INFO] Reason: App failed to load.
[2023-04-04 11:10:20 -0300] [60356] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:7000']
  backlog: 2048
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/real_time_chat_project/chat_service
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: gunicorn.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: asgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f84312ee8c0>
  on_reload: <function OnReload.on_reload at 0x7f84312ee9e0>
  when_ready: <function WhenReady.when_ready at 0x7f84312eeb00>
  pre_fork: <function Prefork.pre_fork at 0x7f84312eec20>
  post_fork: <function Postfork.post_fork at 0x7f84312eed40>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f84312eee60>
  worker_int: <function WorkerInt.worker_int at 0x7f84312eef80>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f84312ef0a0>
  pre_exec: <function PreExec.pre_exec at 0x7f84312ef1c0>
  pre_request: <function PreRequest.pre_request at 0x7f84312ef2e0>
  post_request: <function PostRequest.post_request at 0x7f84312ef370>
  child_exit: <function ChildExit.child_exit at 0x7f84312ef490>
  worker_exit: <function WorkerExit.worker_exit at 0x7f84312ef5b0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f84312ef6d0>
  on_exit: <function OnExit.on_exit at 0x7f84312ef7f0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-04-04 11:10:20 -0300] [60356] [INFO] Starting gunicorn 20.1.0
[2023-04-04 11:10:20 -0300] [60356] [DEBUG] Arbiter booted
[2023-04-04 11:10:20 -0300] [60356] [INFO] Listening at: http://0.0.0.0:7000 (60356)
[2023-04-04 11:10:20 -0300] [60356] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-04-04 11:10:20 -0300] [60357] [INFO] Booting worker with pid: 60357
[2023-04-04 11:10:20 -0300] [60357] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'asgi'
[2023-04-04 11:10:20 -0300] [60357] [INFO] Worker exiting (pid: 60357)
[2023-04-04 11:10:20 -0300] [60356] [INFO] Shutting down: Master
[2023-04-04 11:10:20 -0300] [60356] [INFO] Reason: Worker failed to boot.
[2023-04-04 11:10:52 -0300] [60535] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:7000']
  backlog: 2048
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/real_time_chat_project/chat_service
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: gunicorn.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: asgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f09e18b68c0>
  on_reload: <function OnReload.on_reload at 0x7f09e18b69e0>
  when_ready: <function WhenReady.when_ready at 0x7f09e18b6b00>
  pre_fork: <function Prefork.pre_fork at 0x7f09e18b6c20>
  post_fork: <function Postfork.post_fork at 0x7f09e18b6d40>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f09e18b6e60>
  worker_int: <function WorkerInt.worker_int at 0x7f09e18b6f80>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f09e18b70a0>
  pre_exec: <function PreExec.pre_exec at 0x7f09e18b71c0>
  pre_request: <function PreRequest.pre_request at 0x7f09e18b72e0>
  post_request: <function PostRequest.post_request at 0x7f09e18b7370>
  child_exit: <function ChildExit.child_exit at 0x7f09e18b7490>
  worker_exit: <function WorkerExit.worker_exit at 0x7f09e18b75b0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f09e18b76d0>
  on_exit: <function OnExit.on_exit at 0x7f09e18b77f0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-04-04 11:10:52 -0300] [60535] [INFO] Starting gunicorn 20.1.0
[2023-04-04 11:10:52 -0300] [60535] [DEBUG] Arbiter booted
[2023-04-04 11:10:52 -0300] [60535] [INFO] Listening at: http://0.0.0.0:7000 (60535)
[2023-04-04 11:10:52 -0300] [60535] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-04-04 11:10:52 -0300] [60536] [INFO] Booting worker with pid: 60536
[2023-04-04 11:10:52 -0300] [60536] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'asgi'
[2023-04-04 11:10:52 -0300] [60536] [INFO] Worker exiting (pid: 60536)
[2023-04-04 11:10:52 -0300] [60535] [INFO] Shutting down: Master
[2023-04-04 11:10:52 -0300] [60535] [INFO] Reason: Worker failed to boot.
[2023-04-04 11:13:40 -0300] [60813] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:7000']
  backlog: 2048
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/real_time_chat_project/chat_service
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: gunicorn.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: chat.asgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f803417a8c0>
  on_reload: <function OnReload.on_reload at 0x7f803417a9e0>
  when_ready: <function WhenReady.when_ready at 0x7f803417ab00>
  pre_fork: <function Prefork.pre_fork at 0x7f803417ac20>
  post_fork: <function Postfork.post_fork at 0x7f803417ad40>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f803417ae60>
  worker_int: <function WorkerInt.worker_int at 0x7f803417af80>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f803417b0a0>
  pre_exec: <function PreExec.pre_exec at 0x7f803417b1c0>
  pre_request: <function PreRequest.pre_request at 0x7f803417b2e0>
  post_request: <function PostRequest.post_request at 0x7f803417b370>
  child_exit: <function ChildExit.child_exit at 0x7f803417b490>
  worker_exit: <function WorkerExit.worker_exit at 0x7f803417b5b0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f803417b6d0>
  on_exit: <function OnExit.on_exit at 0x7f803417b7f0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-04-04 11:13:40 -0300] [60813] [INFO] Starting gunicorn 20.1.0
[2023-04-04 11:13:40 -0300] [60813] [DEBUG] Arbiter booted
[2023-04-04 11:13:40 -0300] [60813] [INFO] Listening at: http://0.0.0.0:7000 (60813)
[2023-04-04 11:13:40 -0300] [60813] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-04-04 11:13:40 -0300] [60816] [INFO] Booting worker with pid: 60816
[2023-04-04 11:13:40 -0300] [60816] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'chat.asgi'
[2023-04-04 11:13:40 -0300] [60816] [INFO] Worker exiting (pid: 60816)
[2023-04-04 11:13:40 -0300] [60817] [INFO] Booting worker with pid: 60817
[2023-04-04 11:13:40 -0300] [60817] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/j0k3r/Escritorio/j0k3r/Facultad/Cuarto/Proyecto_INGSOFT/chat_project/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'chat.asgi'
[2023-04-04 11:13:40 -0300] [60817] [INFO] Worker exiting (pid: 60817)
[2023-04-04 11:13:40 -0300] [60813] [WARNING] Worker with pid 60817 was terminated due to signal 15
[2023-04-04 11:13:40 -0300] [60813] [INFO] Shutting down: Master
[2023-04-04 11:13:40 -0300] [60813] [INFO] Reason: Worker failed to boot.
